name: master pipeline

on: push

jobs:
    analyse:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - run: |
                  echo "latest_tag={git describe --tags}" >> $GITHUB_ENV
                  git tag mono-commit-${{ github.sha }}
                  echo "current_tag=${git describe --tags}" >> $GITHUB_ENV
                  echo "test1_tag=$(git describe --tags)" >> $GITHUB_ENV
                  echo "test2_tag=$({git describe --tags})" >> $GITHUB_ENV
                  git push origin --tags
                  git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit
                  echo #### diffs ####
                  echo $current_tag
                  echo $latest_tag
                  echo $test1_tag
                  echo $test2_tag
            - name: Invoke workflow with inputs
              uses: benc-uk/workflow-dispatch@v1
              with:
                  workflow: Other
                  token: ${{ secrets.PIPELINE }}
