name: master pipeline

on: push

jobs:
    analyse:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - run: |
                  LATEST_TAG="$(echo git describe --tags)"
                  echo $LATEST_TAG
                  # git tag mono-commit-${{ github.sha }}
                  # echo "current_tag=$(git describe --tags)" >> $GITHUB_ENV
                  # git push origin --tags
                  # git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit
                  # echo #### diffs ####
                  # echo $current_tag
                  # echo $latest_tag
            - name: Invoke workflow with inputs
              uses: benc-uk/workflow-dispatch@v1
              with:
                  workflow: Other
                  token: ${{ secrets.PIPELINE }}
