name: master pipeline

on: push

jobs:
    analyse:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - run: |
                  LATEST_TAG="$(git describe --tags --abbrev=0)" || true
                  git tag mono-commit-${{ github.sha }}
                  CURRENT_TAG="$(git describe --tags)"
                  git push origin --tags
                  echo "diffs"
                  PACKAGES_CHANGED="(git diff $LATEST_TAG $CURRENT_TAG --stat | grep packages)" || true
                  echo $PACKAGES_CHANGED
            # - name: Invoke workflow with inputs
            #   uses: benc-uk/workflow-dispatch@v1
            #   with:
            #       workflow: Other
            #       token: ${{ secrets.PIPELINE }}
